on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run AGI for 5s
        run: |
          set +e

          timeout 5s python3 strawberry.py
          exit_code=$?

          if [ $exit_code -eq 124 ]; then
            echo "Key Interrupt (timeout) - Success"
            exit 0
          else
            echo "Unexpected exit code: $exit_code"
            exit 1
          fi
